# Generated by Django 5.2.7 on 2025-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_guardian_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
